//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBilet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineBiletEntities : DbContext
    {
        public OnlineBiletEntities()
            : base("name=OnlineBiletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dbo_YolcuYasDurumu> dbo_YolcuYasDurumu { get; set; }
        public DbSet<Hareket> Hareket { get; set; }
        public DbSet<KalkisDurumu> KalkisDurumu { get; set; }
        public DbSet<Kart> Kart { get; set; }
        public DbSet<Pesin> Pesin { get; set; }
        public DbSet<Taksit> Taksit { get; set; }
        public DbSet<VarisDurumu> VarisDurumu { get; set; }
        public DbSet<YolcuBilgileri> YolcuBilgileri { get; set; }
    }
}
